export const GET_NOTEPADS = 'GET_NOTEPADS';
export const GET_NOTEPADS_SUCCESS = 'GET_NOTEPADS_SUCCESS';
export const GET_NOTEPADS_FAILURE = 'GET_NOTEPADS_FAILURE';

export const SAVE_NOTEPAD = 'SAVE_NOTEPAD';
export const SAVE_NOTEPAD_SUCCESS = 'SAVE_NOTEPAD_SUCCESS';
export const SAVE_NOTEPAD_FAILURE = 'SAVE_NOTEPAD_FAILURE';

export const GET_NOTEPAD = 'GET_NOTEPAD';
export const GET_NOTEPAD_SUCCESS = 'GET_NOTEPAD_SUCCESS';
export const GET_NOTEPAD_FAILURE = 'GET_NOTEPAD_FAILURE';

export const UPDATE_NOTEPAD = 'UPDATE_NOTEPAD';
export const UPDATE_NOTEPAD_SUCCESS = 'UPDATE_NOTEPAD_SUCCESS';
export const UPDATE_NOTEPAD_FAILURE = 'UPDATE_NOTEPAD_FAILURE';

export const DELETE_NOTEPAD = 'DELETE_NOTEPAD';
export const DELETE_NOTEPAD_SUCCESS = 'DELETE_NOTEPAD_SUCCESS';
export const DELETE_NOTEPAD_FAILURE = 'DELETE_NOTEPAD_FAILURE';

export const SAVE_NOTE = 'SAVE_NOTE';
export const SAVE_NOTE_SUCCESS = 'SAVE_NOTE_SUCCESS';
export const SAVE_NOTE_FAILURE = 'SAVE_NOTE_FAILURE';

export const GET_NOTE = 'GET_NOTE';
export const GET_NOTE_SUCCESS = 'GET_NOTE_SUCCESS';
export const GET_NOTE_FAILURE = 'GET_NOTE_FAILURE';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';